const GROQ_URL="https://api.groq.com/openai/v1/chat/completions";
const GEOAPIFY_URL="https://api.geoapify.com/v2/places";
const ROUTE_MATRIX_URL="https://api.geoapify.com/v1/routematrix";

const INTENTS={
  restaurant:{words:["food","eat","restaurant","dinner","lunch","breakfast","brunch","hungry","meal"],geo:["catering.restaurant","catering.fast_food"],osm:[["amenity","restaurant"],["amenity","fast_food"]]},
  pizza:{words:["pizza","pizzeria"],geo:["catering.restaurant.pizza","catering.fast_food.pizza"],osm:[["cuisine","pizza"]]},
  cafe:{words:["coffee","cafe","café","latte","tea"],geo:["catering.cafe","catering.cafe.coffee"],osm:[["amenity","cafe"]]},
  dessert:{words:["dessert","ice cream","donut","bakery","sweet"],geo:["catering.cafe.dessert","catering.cafe.ice_cream","commercial.food_and_drink.bakery"],osm:[["amenity","ice_cream"],["shop","bakery"]]},
  bowling:{words:["bowling","bowl"],geo:["entertainment.bowling_alley"],osm:[["leisure","bowling_alley"]]},
  arcade:{words:["arcade","video games","game place","gaming"],geo:["entertainment.amusement_arcade","commercial.toy_and_game"],osm:[["leisure","amusement_arcade"]]},
  cinema:{words:["movie","movies","cinema","theater","theatre"],geo:["entertainment.cinema"],osm:[["amenity","cinema"]]},
  park:{words:["park","outside","outdoors","walk","nature","scenic","view","trail"],geo:["leisure.park","leisure.park.nature_reserve","tourism.attraction"],osm:[["leisure","park"],["leisure","nature_reserve"],["tourism","viewpoint"]]},
  thrift:{words:["thrift","second hand","secondhand","used store"],geo:["commercial.second_hand"],osm:[["shop","second_hand"]]},
  museum:{words:["museum","gallery","art"],geo:["entertainment.museum","entertainment.culture.gallery"],osm:[["tourism","museum"],["tourism","gallery"]]},
  library:{words:["library","books"],geo:["education.library","commercial.books"],osm:[["amenity","library"],["shop","books"]]},
  gym:{words:["gym","fitness","workout","exercise"],geo:["sport.fitness.fitness_centre","sport.fitness.gym"],osm:[["leisure","fitness_centre"]]},
  mini_golf:{words:["mini golf","minigolf","putt putt"],geo:["entertainment.miniature_golf"],osm:[["leisure","miniature_golf"]]},
  escape_room:{words:["escape room","escape game"],geo:["entertainment.escape_game"],osm:[["leisure","escape_game"]]},
  shopping:{words:["shopping","shop","store","stores","mall","retail","buy stuff","go shopping"],geo:["commercial.shopping_mall","commercial"],osm:[["shop",null],["shop","mall"]]},
  attraction:{words:["fun","something to do","activity","adventure","entertainment","friends","date idea","cool place","bored"],geo:["entertainment","tourism.attraction","leisure.park"],osm:[["tourism","attraction"],["leisure",null],["amenity","cinema"]]}
};

const FUN_VARIETY_KEYS=["arcade","bowling","mini_golf","escape_room","cinema","museum","park","attraction"];
const POPULAR_BRANDS=[
  ["walmart",100],["target",99],["costco",98],["sams club",96],["dollar general",95],["dollar tree",94],["ross dress for less",94],["ross",93],["tj maxx",93],["t j maxx",93],["marshalls",93],["burlington",92],["best buy",92],["five below",91],["belk",91],["burkes outlet",90],["bealls",90],["kohls",90],["kohl s",90],["macys",90],["macy s",90],["jcpenney",89],["j c penney",89],["old navy",88],["gap",87],["nike",88],["adidas",87],["home depot",89],["lowes",89],["lowe s",89],["ace hardware",84],["aldi",88],["publix",89],["kroger",88],["food lion",86],["whole foods",88],["trader joes",89],["trader joe s",89],["walgreens",86],["cvs",86],["staples",82],["office depot",82],["petsmart",84],["petco",84],["michaels",84],["hobby lobby",84],["ulta",87],["sephora",88],["academy sports",87],["dicks sporting goods",87],["dick s sporting goods",87],["tractor supply",84],["family dollar",86]
];
const POPULAR_FOOD=[
  ["mcdonalds",90],["mcdonald s",90],["chick fil a",92],["starbucks",92],["taco bell",87],["wendys",87],["wendy s",87],["burger king",86],["subway",84],["chipotle",89],["panera",86],["dominos",86],["domino s",86],["pizza hut",84],["popeyes",86],["sonic",84],["dunkin",87],["waffle house",86],["olive garden",85],["texas roadhouse",87]
];

function clamp(n,min,max){return Math.min(max,Math.max(min,Number(n)||min));}
function milesBetween(a,b,c,d){const R=3958.8,r=n=>n*Math.PI/180,x=r(c-a),y=r(d-b),q=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function cleanJson(text){const s=String(text||"").trim();try{return JSON.parse(s)}catch(_){}const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a>=0&&b>a){try{return JSON.parse(s.slice(a,b+1))}catch(_){}}return null;}
function normalizeMode(m){return ["drive","walk","bicycle"].includes(m)?m:"drive";}
function norm(s){return String(s||"").toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();}
function detectIntentKeys(prompt){const p=String(prompt).toLowerCase(),hits=[];for(const [k,s] of Object.entries(INTENTS))if(s.words.some(w=>p.includes(w)))hits.push(k);if(!hits.length)hits.push("attraction");if(hits.includes("pizza"))return ["pizza"];return [...new Set(hits)].slice(0,3);}
function simpleInterpretation(prompt){const p=String(prompt||"").trim(),tm=p.match(/(?:within|under|less than|no more than|about)?\s*(\d+(?:\.\d+)?)\s*(?:min|mins|minute|minutes)\b/i);let travelMode=null;if(/\b(walk|walking|on foot)\b/i.test(p))travelMode="walk";else if(/\b(bike|biking|bicycle|cycling|cycle)\b/i.test(p))travelMode="bicycle";else if(/\b(drive|driving|car)\b/i.test(p))travelMode="drive";return{summary:p||"something fun nearby",intentKeys:detectIntentKeys(p),maxTravelMinutes:tm?clamp(tm[1],5,90):null,travelMode,openNow:/open now|right now|currently open|tonight|late night/i.test(p)};}
async function interpretWithAI(prompt){const fallback=simpleInterpretation(prompt);if(!process.env.GROQ_API_KEY)return fallback;const allowed=Object.keys(INTENTS).join(", "),system=`Interpret a request for nearby real-world places. Return ONLY JSON: {"summary":"...","intentKeys":["..."],"maxTravelMinutes":number|null,"travelMode":"drive"|"walk"|"bicycle"|null,"openNow":boolean}. Allowed intentKeys: ${allowed}. Pick 1-3. Never invent business names. Use attraction for vague fun/activity requests. Use shopping for broad retail requests. Extract a minute limit only when the user actually gives one.`;try{const r=await fetch(GROQ_URL,{method:"POST",headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"openai/gpt-oss-20b",temperature:.2,max_completion_tokens:400,response_format:{type:"json_object"},messages:[{role:"system",content:system},{role:"user",content:prompt}]})});if(!r.ok)return fallback;const d=await r.json(),j=cleanJson(d?.choices?.[0]?.message?.content);if(!j)return fallback;const keys=Array.isArray(j.intentKeys)?j.intentKeys.filter(k=>INTENTS[k]).slice(0,3):[];return{summary:String(j.summary||fallback.summary).slice(0,180),intentKeys:keys.length?keys:fallback.intentKeys,maxTravelMinutes:j.maxTravelMinutes==null?fallback.maxTravelMinutes:clamp(j.maxTravelMinutes,5,90),travelMode:j.travelMode?normalizeMode(j.travelMode):fallback.travelMode,openNow:Boolean(j.openNow)}}catch(_){return fallback;}}
function withTimeout(p,ms=8500){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error("timeout")),ms))]);}
function sourceQueryLabel(keys){return keys.map(k=>k.replaceAll("_"," ")).join(", ");}
function searchRadiusFor(minutes,mode){const m=mode==="walk"?145:mode==="bicycle"?430:1550;return Math.min(50000,Math.max(1800,Math.round(minutes*m)));}
function isBroadFun(keys){return keys.length===1&&keys[0]==="attraction"||keys.includes("attraction")&&keys.length<=2;}
function expandedKeys(keys){return isBroadFun(keys)?FUN_VARIETY_KEYS:[...new Set(keys)];}
function typeBucket(type){const t=norm(type);if(t.includes("arcade")||t.includes("game"))return"arcade";if(t.includes("bowling"))return"bowling";if(t.includes("miniature golf")||t.includes("mini golf"))return"mini golf";if(t.includes("escape"))return"escape room";if(t.includes("cinema")||t.includes("movie"))return"movies";if(t.includes("museum")||t.includes("gallery"))return"museum";if(t.includes("park")||t.includes("nature")||t.includes("viewpoint"))return"park";if(t.includes("restaurant")||t.includes("food"))return"food";return t.split(" ").slice(0,2).join(" ")||"other";}
function brandMatchScore(name,list){const n=norm(name);let best=0;for(const [brand,score] of list){const b=norm(brand);if(n===b||n.startsWith(b+" ")||n.includes(" "+b+" ")||n.endsWith(" "+b))best=Math.max(best,score)}return best;}
function popularityScore(place,intentKeys,prompt){const n=norm(place.name),q=norm(prompt);let score=0;if(intentKeys.includes("shopping"))score=Math.max(score,brandMatchScore(n,POPULAR_BRANDS));if(intentKeys.some(k=>["restaurant","pizza","cafe","dessert"].includes(k)))score=Math.max(score,brandMatchScore(n,POPULAR_FOOD));for(const [brand] of [...POPULAR_BRANDS,...POPULAR_FOOD]){const b=norm(brand);if(b.length>=3&&q.includes(b)&&n.includes(b))score=Math.max(score,140)}if(place.websiteUri)score+=3;return score;}

async function geoapifySearch(keys,lat,lng,radiusMeters,limit){if(!process.env.GEOAPIFY_API_KEY)throw new Error("geoapify key missing");const cats=[...new Set(keys.flatMap(k=>INTENTS[k]?.geo||[]))].slice(0,18).join(","),u=new URL(GEOAPIFY_URL);u.searchParams.set("categories",cats||"entertainment,tourism.attraction");u.searchParams.set("filter",`circle:${lng},${lat},${Math.round(radiusMeters)}`);u.searchParams.set("bias",`proximity:${lng},${lat}`);u.searchParams.set("limit",String(Math.min(60,Math.max(limit*4,28))));u.searchParams.set("apiKey",process.env.GEOAPIFY_API_KEY);const r=await withTimeout(fetch(u),9000);if(!r.ok)throw new Error(`Geoapify ${r.status}`);const data=await r.json();return(data.features||[]).map(f=>{const p=f.properties||{},c=f.geometry?.coordinates||[],lon=Number(c[0]??p.lon),la=Number(c[1]??p.lat);if(!Number.isFinite(la)||!Number.isFinite(lon))return null;const name=p.name||p.address_line1||"Place",address=p.formatted||p.address_line2||"Address unavailable",addressKey=norm([p.housenumber,p.street,p.city,p.postcode].filter(Boolean).join(" ")||p.address_line2||address),categories=Array.isArray(p.categories)?p.categories:[];return{id:p.place_id||`${la},${lon}`,name,address,addressKey,lat:la,lng:lon,type:categories[0]||"place",categories,websiteUri:p.website||p.datasource?.raw?.website||null}}).filter(Boolean);}
function osmClauses(keys,radius,lat,lng){const parts=[],seen=new Set();for(const key of keys)for(const [tag,val] of(INTENTS[key]?.osm||[])){const sig=`${tag}:${val||"*"}`;if(seen.has(sig))continue;seen.add(sig);const filter=val==null?`["${tag}"]`:`["${tag}"="${val}"]`;parts.push(`nwr${filter}(around:${radius},${lat},${lng});`)}return parts.length?parts:[`nwr["tourism"="attraction"](around:${radius},${lat},${lng});`];}
async function overpassSearch(keys,lat,lng,radiusMeters){const query=`[out:json][timeout:8];(${osmClauses(keys,Math.round(radiusMeters),lat,lng).join("")});out center tags;`,endpoints=["https://overpass.private.coffee/api/interpreter","https://overpass-api.de/api/interpreter","https://maps.mail.ru/osm/tools/overpass/api/interpreter"];let last;for(const ep of endpoints){try{const r=await withTimeout(fetch(ep,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8","User-Agent":"WhatNow/2.2"},body:"data="+encodeURIComponent(query)}),7500);if(!r.ok)throw new Error(`Overpass ${r.status}`);const data=await r.json();return(data.elements||[]).map(el=>{const la=Number(el.lat??el.center?.lat),lon=Number(el.lon??el.center?.lon),t=el.tags||{};if(!Number.isFinite(la)||!Number.isFinite(lon))return null;const name=t.name||t.brand||t.operator;if(!name)return null;const address=[t["addr:housenumber"],t["addr:street"],t["addr:city"],t["addr:state"]].filter(Boolean).join(" ")||t["addr:full"]||"Address unavailable",addressKey=norm([t["addr:housenumber"],t["addr:street"],t["addr:city"],t["addr:postcode"]].filter(Boolean).join(" ")||address),type=t.amenity||t.leisure||t.shop||t.tourism||"place";return{id:`osm-${el.type}-${el.id}`,name,address,addressKey,lat:la,lng:lon,type,categories:[type],websiteUri:t.website||t["contact:website"]||null}}).filter(Boolean)}catch(e){last=e}}throw last||new Error("Overpass unavailable");}
function dedupeRaw(raw,origin,radiusMiles,diverse=false){const out=[];for(const p of raw){if(!Number.isFinite(p.lat)||!Number.isFinite(p.lng))continue;const straightMiles=milesBetween(origin.lat,origin.lng,p.lat,p.lng);if(straightMiles>radiusMiles)continue;const nameKey=norm(p.name),addressKey=p.addressKey||norm(p.address),duplicate=out.some(x=>{const sep=milesBetween(x.lat,x.lng,p.lat,p.lng),sameName=nameKey&&nameKey===x._nameKey,sameAddress=addressKey&&addressKey!=="address unavailable"&&addressKey===x._addressKey;return sameName&&sep<.35||sameAddress&&sep<.12||sep<.012||diverse&&sep<.055});if(duplicate)continue;out.push({...p,straightMiles,_nameKey:nameKey,_addressKey:addressKey,_bucket:typeBucket((p.categories||[]).join(" ")+" "+p.type)})}return out.slice(0,60);}
function estimateMinutes(miles,mode){if(mode==="walk")return Math.max(2,Math.round(miles/3*60*1.08));if(mode==="bicycle")return Math.max(2,Math.round(miles/12*60*1.1));return Math.max(3,Math.round(miles/28*60+2));}
async function addRouteTimes(places,origin,mode){if(!places.length)return{places,routeTimeSource:"none"};if(process.env.GEOAPIFY_API_KEY){try{const url=`${ROUTE_MATRIX_URL}?apiKey=${encodeURIComponent(process.env.GEOAPIFY_API_KEY)}`,body={mode,sources:[{location:[origin.lng,origin.lat]}],targets:places.map(p=>({location:[p.lng,p.lat]}))},r=await withTimeout(fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),10000);if(!r.ok)throw new Error(`Route Matrix ${r.status}`);const data=await r.json();let row=data.sources_to_targets||[];if(Array.isArray(row[0]))row=row[0];return{places:places.map((p,i)=>{const cell=row[i]||{},seconds=Number(cell.time),distanceMeters=Number(cell.distance);return Number.isFinite(seconds)&&seconds>=0?{...p,travelMinutes:Math.max(1,Math.round(seconds/60)),routeDistanceMeters:Number.isFinite(distanceMeters)?distanceMeters:null,travelTimeEstimated:false}:{...p,travelMinutes:estimateMinutes(p.straightMiles,mode),routeDistanceMeters:null,travelTimeEstimated:true}}),routeTimeSource:"Geoapify Route Matrix"}}catch(_){}}return{places:places.map(p=>({...p,travelMinutes:estimateMinutes(p.straightMiles,mode),routeDistanceMeters:null,travelTimeEstimated:true})),routeTimeSource:"estimated"};}
function chooseVaried(sorted,limit,diverse){if(!diverse)return sorted.slice(0,limit);const chosen=[],left=[],counts=new Map();for(const p of sorted){const b=p._bucket||"other",c=counts.get(b)||0;if(c<2){chosen.push(p);counts.set(b,c+1)}else left.push(p);if(chosen.length>=limit)return chosen}for(const p of left){if(chosen.length>=limit)break;chosen.push(p)}return chosen;}
function finishPlaces(places,mode,maxMinutes,limit,diverse,intentKeys,prompt){const travelmode=mode==="walk"?"walking":mode==="bicycle"?"bicycling":"driving",shopping=intentKeys.includes("shopping"),sorted=places.filter(p=>Number.isFinite(p.travelMinutes)&&p.travelMinutes<=maxMinutes).map(p=>({...p,_popularity:popularityScore(p,intentKeys,prompt)})).sort((a,b)=>{if(shopping){const aa=a.travelMinutes-Math.min(16,a._popularity/6.5),bb=b.travelMinutes-Math.min(16,b._popularity/6.5);return aa-bb||b._popularity-a._popularity||a.travelMinutes-b.travelMinutes}return a.travelMinutes-b.travelMinutes||b._popularity-a._popularity||a.straightMiles-b.straightMiles});return chooseVaried(sorted,limit,diverse).map((p,i)=>({id:p.id,name:p.name,address:p.address,lat:p.lat,lng:p.lng,type:p.type,websiteUri:p.websiteUri||null,travelMinutes:p.travelMinutes,travelTimeEstimated:p.travelTimeEstimated,routeDistanceMeters:p.routeDistanceMeters||null,bestPick:i===0,popular:p._popularity>=80,popularityScore:p._popularity,mapsUri:`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}&travelmode=${travelmode}`,webSearchUri:`https://www.google.com/search?q=${encodeURIComponent(`${p.name} ${p.address||""}`)}`}));}

export default async function handler(req,res){if(req.method!=="POST"){res.setHeader("Allow","POST");return res.status(405).json({error:"Method not allowed"})}try{const{prompt,lat,lng,maxTravelMinutes=20,travelMode="drive",maxResults=12}=req.body||{},text=String(prompt||"").trim(),latitude=Number(lat),longitude=Number(lng);if(!text)return res.status(400).json({error:"Tell WhatNow what you want to do."});if(!Number.isFinite(latitude)||!Number.isFinite(longitude))return res.status(400).json({error:"Your location is required."});const uiMinutes=clamp(maxTravelMinutes,5,60),limit=Math.round(clamp(maxResults,4,20)),ai=await interpretWithAI(text),mode=ai.travelMode||normalizeMode(travelMode),effectiveMinutes=ai.maxTravelMinutes?Math.min(uiMinutes,ai.maxTravelMinutes):uiMinutes,diverse=isBroadFun(ai.intentKeys),searchKeys=expandedKeys(ai.intentKeys),radiusMeters=searchRadiusFor(effectiveMinutes,mode),radiusMiles=radiusMeters/1609.344,shopping=ai.intentKeys.includes("shopping");let raw=[],source="OpenStreetMap",warning=null;if(process.env.GEOAPIFY_API_KEY){try{raw=await geoapifySearch(searchKeys,latitude,longitude,radiusMeters,limit);source="Geoapify"}catch(_){warning="Geoapify Places had a problem, so I used the OpenStreetMap backup."}}if(shopping||raw.length<Math.min(12,limit*2)){try{const osm=await overpassSearch(searchKeys,latitude,longitude,radiusMeters);raw=raw.concat(osm);if(source==="Geoapify"&&osm.length)source="Geoapify + OpenStreetMap";else if(source!=="Geoapify")source="OpenStreetMap"}catch(_){if(!raw.length)warning="Live place providers were busy. Use the Maps/web fallbacks below."}}const origin={lat:latitude,lng:longitude},candidates=dedupeRaw(raw,origin,radiusMiles,diverse),routed=await addRouteTimes(candidates,origin,mode),places=finishPlaces(routed.places,mode,effectiveMinutes,limit,diverse,ai.intentKeys,text);if(routed.routeTimeSource==="estimated"&&!warning)warning="Travel times are estimated because live routing was unavailable.";const query=diverse?"fun things to do":sourceQueryLabel(ai.intentKeys)||text,fallbackMapUrl=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`,fallbackWebUrl=`https://www.google.com/search?q=${encodeURIComponent(`${text} near me`)}`;res.setHeader("Cache-Control","no-store");return res.status(200).json({understood:ai.summary,queries:ai.intentKeys,maxTravelMinutes:effectiveMinutes,travelMode:mode,places,source,routeTimeSource:routed.routeTimeSource,warning:places.length?warning:(warning||`No place matched within ${effectiveMinutes} minutes.`),fallbackMapUrl,fallbackWebUrl,needsGeoapifyKey:!process.env.GEOAPIFY_API_KEY,aiEnabled:Boolean(process.env.GROQ_API_KEY),diversified:diverse,popularityBoost:shopping})}catch(e){console.error(e);return res.status(500).json({error:"WhatNow search failed. Try again."})}}
